import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  integer,
  date,
  timestamp,
  pgEnum,
} from "drizzle-orm/pg-core";

import { files } from "./files.js";
import { users } from "./users.js";
import { checklists } from "./checklist.js";

export const queryPriorityEnum = pgEnum("query_priority_enum", [
  "Low",
  "Medium",
  "High",
]);

export const queryStatusEnum = pgEnum("query_status_enum", [
  "Open",
  "In Progress",
  "Resolved",
]);

export const queries = pgTable("queries", {
  id: uuid("id").defaultRandom().primaryKey(),

  queryNumber: varchar("query_number", { length: 30 }).notNull().unique(),

  fileId: uuid("file_id")
    .notNull()
    .references(() => files.id),

  title: varchar("title", { length: 500 }).notNull(),

  description: text("description"),

  priority: queryPriorityEnum("priority").notNull().default("Medium"),

  status: queryStatusEnum("status").notNull().default("Open"),

  raisedBy: uuid("raised_by")
    .notNull()
    .references(() => users.id),

  assignedTo: uuid("assigned_to").references(() => users.id),

  dueDate: date("due_date"),

  resolvedAt: timestamp("resolved_at", { withTimezone: true }),

  resolvedBy: uuid("resolved_by").references(() => users.id),

  resolutionText: text("resolution_text"),

  daysTaken: integer("days_taken"),

  autoGenerated: boolean("auto_generated").notNull().default(false),

  checklistRef: varchar("checklist_ref", { length: 50 }),

  checklistId: uuid("checklist_id").references(() => checklists.id),

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),

  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});