import { db } from "../db/index.js";
import { queries } from "../db/schema/queries.js";
import { users } from "../db/schema/users.js";
import { roles } from "../db/schema/roles.js";
import { files } from "../db/schema/files.js";
import { queryAttachments } from "../db/schema/query_attachments.js";
import { eq, and, isNull } from "drizzle-orm";
import { alias } from "drizzle-orm/pg-core";

// ─────────────────────────────────────────────────────────────────────────────
// GET — single query detail by queryId
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetches full details of a single query by its UUID.
 *
 * This powers the query detail panel — the header bar (query number,
 * priority, status, raised by, assigned to, dates, file reference)
 * plus the description card and its query-level attachments (metadata only).
 *
 * Queries:
 *   1. Main query with JOINs to resolve raiser, assignee, and resolver
 *      names/roles, and the parent file number.
 *   2. Query-level attachments (reply_id IS NULL) — metadata only,
 *      no download URLs. The frontend calls a dedicated download
 *      endpoint on user action.
 *
 * Join chain (query 1):
 *   queries
 *     INNER JOIN files                ON queries.file_id     = files.id
 *     INNER JOIN users  (raiser)      ON queries.raised_by   = users.id
 *     INNER JOIN roles  (raiserRole)  ON raiser.role_id      = roles.id
 *     LEFT  JOIN users  (assignee)    ON queries.assigned_to = users.id
 *     LEFT  JOIN roles  (assigneeRole)ON assignee.role_id    = roles.id
 *     LEFT  JOIN users  (resolver)    ON queries.resolved_by = users.id
 *     LEFT  JOIN roles  (resolverRole)ON resolver.role_id    = roles.id
 *
 * raised_by and file_id are NOT NULL  → INNER JOINs are safe.
 * assigned_to and resolved_by are nullable → LEFT JOINs.
 * Three aliases each for users and roles because raiser, assignee,
 * and resolver are independent user references on the same row.
 *
 * @param {string} queryId - UUID of the query
 * @returns {Promise<Object>} Full query detail with attachments
 *
 * @throws {Error} .statusCode = 404 — query not found
 */
export const getQueryDetail = async (queryId) => {
  // ── Aliases for multiple user/role joins ─────────────────────────────────
  const raiserUser = alias(users, "raiser_user");
  const raiserRole = alias(roles, "raiser_role");
  const assigneeUser = alias(users, "assignee_user");
  const assigneeRole = alias(roles, "assignee_role");
  const resolverUser = alias(users, "resolver_user");
  const resolverRole = alias(roles, "resolver_role");

  // ── Query 1: Main details ───────────────────────────────────────────────
  const [row] = await db
    .select({
      // query fields
      id: queries.id,
      queryNumber: queries.queryNumber,
      title: queries.title,
      description: queries.description,
      priority: queries.priority,
      status: queries.status,
      dueDate: queries.dueDate,
      autoGenerated: queries.autoGenerated,
      checklistId: queries.checklistId,
      createdAt: queries.createdAt,
      resolvedAt: queries.resolvedAt,
      resolutionText: queries.resolutionText,
      daysTaken: queries.daysTaken,

      // file
      fileId: files.id,
      fileNumber: files.fileNumber,

      // raiser (NOT NULL — always present)
      raiserId: raiserUser.id,
      raiserName: raiserUser.name,
      raiserRoleName: raiserRole.name,

      // assignee (nullable)
      assigneeId: assigneeUser.id,
      assigneeName: assigneeUser.name,
      assigneeRoleName: assigneeRole.name,

      // resolver (nullable)
      resolverId: resolverUser.id,
      resolverName: resolverUser.name,
      resolverRoleName: resolverRole.name,
    })
    .from(queries)
    .innerJoin(files, eq(queries.fileId, files.id))
    .innerJoin(raiserUser, eq(queries.raisedBy, raiserUser.id))
    .innerJoin(raiserRole, eq(raiserUser.roleId, raiserRole.id))
    .leftJoin(assigneeUser, eq(queries.assignedTo, assigneeUser.id))
    .leftJoin(assigneeRole, eq(assigneeUser.roleId, assigneeRole.id))
    .leftJoin(resolverUser, eq(queries.resolvedBy, resolverUser.id))
    .leftJoin(resolverRole, eq(resolverUser.roleId, resolverRole.id))
    .where(eq(queries.id, queryId))
    .limit(1);

  if (!row) {
    const err = new Error("Query not found");
    err.statusCode = 404;
    throw err;
  }

  // ── Query 2: Query-level attachments (reply_id IS NULL) ─────────────────
  // Only metadata — no download URLs. The frontend calls the dedicated
  // download endpoint when the user clicks "Download".
  const attachmentRows = await db
    .select({
      id: queryAttachments.id,
      fileName: queryAttachments.fileName,
      fileSize: queryAttachments.fileSize,
      mimeType: queryAttachments.mimeType,
    })
    .from(queryAttachments)
    .where(
      and(
        eq(queryAttachments.queryId, queryId),
        isNull(queryAttachments.replyId)
      )
    );

  // ── Shape response ──────────────────────────────────────────────────────
  return {
    id: row.id,
    queryNumber: row.queryNumber,
    title: row.title,
    description: row.description,
    priority: row.priority,
    status: row.status,
    dueDate: row.dueDate,
    autoGenerated: row.autoGenerated,
    checklistId: row.checklistId,
    createdAt: row.createdAt,
    resolvedAt: row.resolvedAt,
    resolutionText: row.resolutionText,
    daysTaken: row.daysTaken,
    file: {
      id: row.fileId,
      fileNumber: row.fileNumber,
    },
    raisedBy: {
      id: row.raiserId,
      name: row.raiserName,
      roleName: row.raiserRoleName,
    },
    assignedTo: row.assigneeId
      ? {
          id: row.assigneeId,
          name: row.assigneeName,
          roleName: row.assigneeRoleName,
        }
      : null,
    resolvedBy: row.resolverId
      ? {
          id: row.resolverId,
          name: row.resolverName,
          roleName: row.resolverRoleName,
        }
      : null,
    attachments: attachmentRows.map((a) => ({
      id: a.id,
      fileName: a.fileName,
      fileSize: a.fileSize,
      mimeType: a.mimeType,
    })),
  };
};